### ISSUE TITLE
Passo 4: Crie uma issue solicitando ser colaborador do repositório: 

### ISSUE THREAD

**Issue by Wsanbey** [ramidedantas/GCMS-2023-2#21]
Olá Professor @ramidedantas,

Espero que esteja tudo bem. Aqui é Welry e sou aluno(a) de sua disciplina GCMS. Gostaria de solicitar gentilmente permissão para acessar seu repositório.

Estou bastante interessado em explorar o conteúdo e recursos disponíveis no repositório, pois acredito que isso pode contribuir significativamente para o meu aprendizado e aprofundar meus conhecimentos na disciplina.

Comprometo-me a utilizar o acesso de forma responsável, obedecendo a todas as diretrizes e restrições determinadas. Agradecimentos antecipados pela atenção dada à minha solicitação.

Atenciosamente, Welry

**Comment by ramidedantas** [comment]
@Wsanbey convite enviado

**Comment by Wsanbey** [comment]
* [x]  Convite enviado **Aceito**
