### ISSUE TITLE
Eu gostaria de solicitar ao professor que adicione meu nome como colaborador na descrição do repositório.

### ISSUE THREAD

**Issue by Wsanbey** [ramidedantas/GCMS-2023-2#22]
# Link do meu repósitoro da PRÁTICA 01
> [MEU README](https://github.com/Wsanbey/GCMS-Welry-Silva.git)

**Comment by ramidedantas** [comment]
@Wsanbey você deve adicionar o seu nome após aceitar o convite. Eu que adiciono o meu nome no seu repositório.
