### ISSUE TITLE
SOLICITAÇÃO DE COLABORAÇÃO

### ISSUE THREAD

**Issue by silvaandrep** [ramidedantas/GCMS-2023-2#7]
@ramidedantas  Solicito ser colaborador do repositório

**Comment by ramidedantas** [comment]
Convite enviado.

**Comment by silvaandrep** [comment]
Inclui meu nome, sobrenome e @login no GitHub na lista de colaboradores do arquivo Readme.md e comitei

**Comment by ramidedantas** [comment]
OK, encerrando issue.
